### ISSUE TITLE
Current license (AGPL) is very restrictive

### ISSUE THREAD

**Issue by rla** [ahungry/semblance#1]
The AGPL license considers web use as distribution and makes proprietary applications impossible and any commercial usage likely unpractical. Please make this clear in the README if this is the actual intention.

http://choosealicense.com/licenses/

**Comment by ahungry** [comment]
Thanks, added some extra comments for the user in the README so they understand what AGPL is before using the code (even though it does restrict the potential audience, I am a large proponent of copyleft, so the license choice is intentional).
